name: getx_pronunciation_checker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.4.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  get: ^4.7.2
  lottie: ^3.3.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  showcaseview: ^4.0.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/lottie/

get_cli:
    sub_folder: false    
